### ISSUE TITLE
UI bug on system theme button

### ISSUE THREAD

**Issue by KristofKekesi** [gaetschwartz/swift_travel#8]
**Describe the bug**
The system text takes 2 lines to fit, with a weird text wrap.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Customisation'
3. Click on 'System'

**Expected behavior**
The text should fit in one line.

**Screenshots**
![IMG_5235](https://user-images.githubusercontent.com/64812024/147694918-7ddbecbb-6fb2-404b-9a55-d166283274b0.jpg)

**Platform (please complete the following information):**
 - Device: iPhone 11
 - OS: 15.2
 - Browser Safari

**Application version:**
- Version: 428

**Comment by KristofKekesi** [comment]
Should be fixed at `_ThememodeWidget`, caused by the border when `mode` is `theme.themeMode`.

Widget:
https://github.com/gaetschwartz/swift_travel/blob/e333695d19fcf3b66c6f42556b2e93c5c416b8f9/app/lib/settings/pages/customization.dart#L157

border:
https://github.com/gaetschwartz/swift_travel/blob/e333695d19fcf3b66c6f42556b2e93c5c416b8f9/app/lib/settings/pages/customization.dart#L188

**Comment by gaetschwartz** [comment]
Thanks for the heads up, will fix as soon as I have time to do so !
